server:
  port: 3344
  
  
spring:
  application:
    name: microserviceloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lilike/microservicecloud-config.git #Github仓库
            